### ISSUE TITLE
NameError: name 'Model' is not defined 

### ISSUE THREAD

**Issue by SeekPoint** [taoshen58/ReSAN#1]
mldl@mldlUB1604:~/ub16_prj/ReSAN/SICK_rl_pub$ python3 sick_rl_main.py 
------------------------------
==>model_title: est
------------------------------
decay: 0.9
dropout: 0.7
rl_sparsity: 0.006
out_channel_dims: 50,50,50
learning_rate: 0.5
gpu_mem: None
glove_corpus: 6B
batch_norm: False

------------------------------
digitizing data: test...
Done
------------------------------
Saving data to /home/mldl/ub16_prj/ReSAN/SICK_rl_pub/result/processed_data/processed_lw_True_ugut_True_gc_6B_wel_300.pickle
Done
Traceback (most recent call last):
  File "sick_rl_main.py", line 127, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "sick_rl_main.py", line 112, in main
    train()
  File "sick_rl_main.py", line 48, in train
    model = Model(emb_mat_token, emb_mat_glove, len(train_data_obj.dicts['token']),
NameError: name 'Model' is not defined
mldl@mldlUB1604:~/ub16_prj/ReSAN/SICK_rl_pub$

**Comment by taoshen58** [comment]
did you follow the running instruction?

**Comment by SeekPoint** [comment]
python3 sick_rl_main.py --network_type resan --base_name resan --model_dir_suffix training --gpu 0
